language: python
sudo: false
python: 2.7

cache:
  directories:
    - $HOME/.cache/pip


env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=flake8
  - TOX_ENV=manifest
  - TOX_ENV=docs

install:
  - pip install tox codecov

script:
  - tox --hashseed 0 -e $TOX_ENV

after_success:
  - codecov
