---

# Don't have two build jobs for each pull request.
trigger:
  - master


jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        lint:
          python.version: '3.7'
          TOXENV: lint
        mypy:
          python.version: '3.7'
          TOXENV: mypy
        manifest:
          python.version: '3.7'
          TOXENV: manifest
        docs:
          python.version: '3.7'
          TOXENV: docs
        pypi-description:
          python.version: '3.7'
          TOXENV: pypi-description

        py27-twisted:
          python.version: '2.7'
          TOXENV: py27-twisted
        py27:
          python.version: '2.7'
          TOXENV: py27
        py34-twisted:
          python.version: '3.4'
          TOXENV: py34-twisted
        py34:
          python.version: '3.4'
          TOXENV: py34
        py35-twisted:
          python.version: '3.5'
          TOXENV: py35-twisted
        py35:
          python.version: '3.5'
          TOXENV: py35
        py36-twisted:
          python.version: '3.6'
          TOXENV: py36-twisted
        py36:
          python.version: '3.6'
          TOXENV: py36
        py37:
          python.version: '3.7'
          TOXENV: py37
        py37-twisted:
          python.version: '3.7'
          TOXENV: py37-twisted
        pypy-twisted:
          python.version: pypy2
          TOXENV: pypy-twisted
        pypy:
          python.version: pypy2
          TOXENV: pypy
        pypy3:
          python.version: pypy3
          TOXENV: pypy3
        pypy3-twisted:
          python.version: pypy3
          TOXENV: pypy3-twisted

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade tox codecov
        displayName: install tox
      - script: env TOX_TEST_EXTRAS=azure-pipelines tox
        displayName: run tox
      - script: |
          coverage combine
          codecov -t $(CODECOV_TOKEN)
        displayName: Report Coverage
        condition: succeeded()
